name: "zizu28 Action in Action"
description: 'Greets someone and returns always 42'
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  answer:
    description: "The answer to everything (always 42)."
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.who-to-greet }}
